export default [
	{ location: 'Abuloma', price: 700 },
	{ location: 'Ada george', price: 600 },
	{ location: 'Amadi', price: 600 },
	{ location: 'Airforce', price: 500 },
	{ location: 'Alakahia', price: 900 },
	{ location: 'Choba', price: 900 },
	{ location: 'D-line', price: 600 },
	{ location: 'Diobu', price: 700 },
	{ location: 'Eagle island', price: 700 },
	{ location: 'Elechi', price: 600 },
	{ location: 'Eleme junction', price: 500 },
	{ location: 'Elelewo', price: 600 },
	{ location: 'Elekahia', price: 500 },
	{ location: 'Fimeama', price: 600 },
	{ location: 'Gra phase 3', price: 600 },
	{ location: 'Igwuruta', price: 900 },
	{ location: 'Mgbosimini', price: 700 },
	{ location: 'Mguoba/nta', price: 700 },
	{ location: 'Nkpogu', price: 500 },
	{ location: 'Nkpolu', price: 600 },
	{ location: 'New Gra', price: 500 },
	{ location: 'Oroworokwo', price: 500 },
	{ location: 'Okilton mboba market', price: 600 },
	{ location: 'Okuruama', price: 600 },
	{ location: 'Ogbunabali', price: 500 },
	{ location: 'Ogbogoro', price: 900 },
	{ location: 'Oyigbo', price: 900 },
	{ location: 'Ozuoba', price: 900 },
	{ location: 'Rumuigbo', price: 500 },
	{ location: 'Rumumasi', price: 500 },
	{ location: 'Rumuibekwe', price: 500 },
	{ location: 'Rumuola', price: 500 },
	{ location: 'Rumuogba', price: 500 },
	{ location: 'Rumuokwuta', price: 500 },
	{ location: 'Rumurolu', price: 500 },
	{ location: 'Rumukoroshe', price: 500 },
	{ location: 'Rumuodomaya', price: 500 },
	{ location: 'Rainbow town', price: 500 },
	{ location: 'Rumuomoi', price: 500 },
	{ location: 'Rumuwaji', price: 500 },
	{ location: 'Rumuopirikom', price: 600 },
	{ location: 'Rukpokwu', price: 700 },
	{ location: 'Rumuokoro', price: 800 },
	{ location: 'Woji', price: 500 }
];
